[project]
name = "tensorflow-caney"
authors = [
    {name = "Jordan A. Caraballo-Vega", email = "jordan.a.caraballo-vega@nasa.gov"},
]
readme = "README.md"
classifiers = [
    "License :: OSI Approved :: Apache License",
]
requires-python = ">=3.7"
dynamic = ["version", "description"]

[build-system]
requires = [
    "setuptools >= 40.6.0",
    "setuptools_scm[toml] >= 4, <6",
    "setuptools_scm_git_archive",
    "wheel",
    "segmentation-models",
    "xarray",
    "rioxarray",
    "numba"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "tensorflow_caney/version.py"

[tool.coverage.run]
branch = true
relative_files = true
source = ['tensorflow_caney']
omit = ['tensorflow_caney/version.py']

[tool.coverage.report]
show_missing = true
fail_under = 95

[tool.black]
line-length = 88
target-version = ['py38']